print (1+10+30)
print (1+10+30+40)
print ("this is a string")
print ("this is a string with a number " + str(100))
print ("this is a string with a number " + str(100) + " and another number " + str(200))
print ("this is a string with a number " + str(100) + " and another number " + str(200) + " and a third number " + str(300))